INSERT INTO Computer (
  ComputerTitle,
  ComputerBrand,
  ComputerSeries,
  ComputerRam,
  ComputerHard,
  ComputerGraphic,
  ComputerWarrenty,
  ComputerPrice,
  ComputerDescription,ComputerStatus,CatagoryID, VirusGuardId
) VALUES (
  'Dell Inspiron 15 3000', 
  'Dell', 
  'Inspiron 15 3000', 
  '8GB', 
  '1TB HDD', 
  'Intel HD Graphics 620', 
  '1 year', 
  105000,
  'The Dell Inspiron 15 3000 is a budget-friendly laptop that offers solid performance, a comfortable keyboard, and decent battery life.',
'Available',3,18), (
  'HP Pavilion x360', 
  'HP', 
  'Pavilion x360', 
  '16GB', 
  '512GB SSD', 
  'Intel UHD Graphics', 
  '2 years', 
  165000,
  'The HP Pavilion x360 is a versatile laptop that can be used as a tablet, with a powerful processor and ample storage space.'
,'Available',3,18), (
  'Asus ROG Zephyrus G14', 
  'Asus', 
  'ROG Zephyrus G14', 
  '16GB', 
  '1TB SSD', 
  'NVIDIA GeForce RTX 2060', 
  '3 years', 
  385000,
  'The Asus ROG Zephyrus G14 is a powerful gaming laptop with a unique design and an excellent battery life.'
,'Available',3,18), (
  'Lenovo IdeaPad 5', 
  'Lenovo', 
  'IdeaPad 5', 
  '8GB', 
  '512GB SSD', 
  'Intel Iris Xe Graphics', 
  '1 year', 
  120000,
  'The Lenovo IdeaPad 5 is a slim and lightweight laptop with a stylish design and good performance.'
,'Available',3,18), (
  'Acer Aspire 5', 
  'Acer', 
  'Aspire 5', 
  '12GB', 
  '1TB HDD', 
  'Intel UHD Graphics', 
  '2 years', 
  125000,
  'The Acer Aspire 5 is a budget-friendly laptop with a decent performance and a comfortable keyboard.'
,'Available',3,18), (
  'MSI GS65 Stealth Thin', 
  'MSI', 
  'GS65 Stealth Thin', 
  '32GB', 
  '1TB SSD', 
  'NVIDIA GeForce RTX 2070', 
  '3 years', 
  450000,
  'The MSI GS65 Stealth Thin is a high-end gaming laptop with a slim and lightweight design and a long battery life.'
,'Available',3,18), (
  'Apple MacBook Pro', 
  'Apple', 
  'MacBook Pro', 
  '16GB', 
  '512GB SSD', 
  'Intel Iris Plus Graphics', 
  '1 year', 
  365000,
  'The Apple MacBook Pro is a premium laptop with a sleek design, a crisp display, and powerful performance.'
,'Available',3,18), (
  'Dell XPS 13', 
  'Dell', 
  'XPS 13', 
  '16GB', 
  '512GB SSD', 
  'Intel UHD Graphics', 
  '2 years', 
  225000,
  'The Dell XPS 13 is a well-built laptop with a compact and lightweight design and a long battery life.'
,'Available',3,18), 
('ASUS VivoBook 14', 'ASUS', 'VivoBook', '8GB', '512GB SSD', 'Intel UHD Graphics', '1 Year', 139990, 'The ASUS VivoBook 14 is a stylish and powerful laptop with an Intel Core i5 processor and a 14 inch Full HD display.','Available',3,18),
('Acer Aspire 5', 'Acer', 'Aspire', '8GB', '256GB SSD', 'Intel UHD Graphics', '1 Year', 119990, 'The Acer Aspire 5 is a slim and lightweight laptop with an Intel Core i3 processor and a 15.6 inch Full HD display.','Available',3,18),
('HP Pavilion x360', 'HP', 'Pavilion', '8GB', '128GB SSD', 'Intel UHD Graphics', '1 Year', 109990, 'The HP Pavilion x360 is a 2-in-1 laptop with a 14 inch Full HD touchscreen display, an Intel Core i3 processor, and 8GB of RAM.','Available',3,18),
('Dell Inspiron 15', 'Dell', 'Inspiron', '4GB', '1TB HDD', 'Intel UHD Graphics', '1 Year', 89990, 'The Dell Inspiron 15 is a budget-friendly laptop with an Intel Celeron processor, 4GB of RAM, and a 15.6 inch HD display.','Available',3,18),
('Lenovo Ideapad 330', 'Lenovo', 'Ideapad', '4GB', '500GB HDD', 'Intel UHD Graphics', '1 Year', 79990, 'The Lenovo Ideapad 330 is an affordable laptop with an Intel Celeron processor, 4GB of RAM, and a 15.6 inch HD display.','Available',1,18),
('HP 15', 'HP', '15', '4GB', '500GB HDD', 'Intel UHD Graphics', '1 Year', 79990, 'The HP 15 is a budget-friendly laptop with an Intel Celeron processor, 4GB of RAM, and a 15.6 inch HD display.','Available',1,18),
('Acer Chromebook Spin 311', 'Acer', 'Chromebook', '4GB', '32GB eMMC', 'Intel UHD Graphics', '1 Year', 89990, 'The Acer Chromebook Spin 311 is a lightweight and portable laptop with an Intel Celeron processor and a 11.6 inch HD touchscreen display.','Available',1,18),
('ASUS VivoBook 15', 'ASUS', 'VivoBook', '4GB', '500GB HDD', 'Intel UHD Graphics', '1 Year', 79990, 'The ASUS VivoBook 15 is a budget-friendly laptop with an Intel Celeron processor, 4GB of RAM, and a 15.6 inch HD display.','Available',1,18),
('Dell Inspiron 14', 'Dell', 'Inspiron', '8GB', '256GB SSD', 'Intel UHD Graphics', '1 Year', 119990, 'The Dell Inspiron 14 is a sleek and powerful laptop with an Intel Core i3 processor and a 14 inch Full HD display.','Available',1,18),

('Dell Optiplex 3070', 'Dell', 'Optiplex', '8 GB', '1 TB HDD', 'Intel UHD Graphics 630', '1 year', 85000, 'Powerful desktop for work and home use', 'Available', 2,18),
('HP EliteDesk 800 G5', 'HP', 'EliteDesk', '16 GB', '512 GB SSD', 'Intel UHD Graphics 630', '2 years', 145000, 'High-end desktop for demanding tasks', 'Available', 2,18),
('Acer Aspire TC-895-UA92', 'Acer', 'Aspire', '12 GB', '512 GB SSD', 'Intel UHD Graphics 630', '1 year', 95000, 'Affordable desktop for everyday use', 'Available', 2,18),
('Lenovo IdeaCentre 3 07ADA', 'Lenovo', 'IdeaCentre', '8 GB', '1 TB HDD', 'AMD Radeon Graphics', '1 year', 78000, 'Budget-friendly desktop with decent specs', 'Available', 2,18),
('Apple Mac Mini', 'Apple', 'Mac Mini', '8 GB', '256 GB SSD', 'Intel UHD Graphics 630', '1 year', 135000, 'Small but powerful desktop for macOS users', 'Available', 2,18),
('Dell Inspiron 3880', 'Dell', 'Inspiron', '8 GB', '256 GB SSD', 'Intel UHD Graphics 630', '1 year', 76000, 'Affordable desktop with modern design', 'Available', 2,18),
('HP Pavilion TP01-1026', 'HP', 'Pavilion', '16 GB', '1 TB HDD', 'Intel UHD Graphics 630', '2 years', 118000, 'Premium-looking desktop with powerful specs', 'Available', 2,18),
('Lenovo ThinkCentre M720', 'Lenovo', 'ThinkCentre', '8 GB', '256 GB SSD', 'Intel UHD Graphics 630', '3 years', 110000, 'Business-class desktop with security features', 'Available', 2,18),
('Acer Veriton M4660G', 'Acer', 'Veriton', '8 GB', '1 TB HDD', 'Intel UHD Graphics 630', '1 year', 87000, 'Reliable desktop for work and home use', 'Available', 2,18),
('Asus ROG Strix GA15DH', 'Asus', 'ROG Strix', '16 GB', '512 GB SSD', 'NVIDIA GeForce GTX 1660', '2 years', 190000, 'Gaming desktop with powerful graphics', 'Available', 2,18),
('HP Slim Desktop S01', 'HP', 'Slim Desktop', '8 GB', '1 TB HDD', 'Intel UHD Graphics 630', '1 year', 74000, 'Compact and affordable desktop for basic tasks', 'Available', 2,18);
